server:
  port: 80
  servlet:
    context-path: /fastdfs
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_file?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123123
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:
    width: 150
    height: 150
  tracker-list:
    - 192.168.64.128:22122
mybatis:
  configuration:
    map-underscore-to-camel-case: true


